tasks:
  - init: git remote set-url origin git@github.com:Pass1-2-3/Test_repo_2.git && sed "s/\r$//" commit-command.sh | bash && gp open README.md
vscode:
 extensions:
   - redhat.java
   - vscjava.vscode-java-debug
   - kyntrack.rev-test-run